name: Build custom_spider.jar

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build JAR
      run: |
        chmod +x gradlew
        ./gradlew buildAndGenJar --no-daemon --stacktrace --info

    - name: Verify JAR
      run: |
        if [ ! -f "jar/custom_spider.jar" ]; then
          echo "JAR 生成失败！"
          ls -la jar/ || true
          exit 1
        fi
        echo "custom_spider.jar 生成成功！"

    - name: Generate MD5
      run: |
        echo "$(openssl md5 -hex jar/custom_spider.jar | awk '{print $2}')" > jar/custom_spider.jar.md5

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: custom_spider.jar
        path: jar/custom_spider.jar

    - name: Commit & Push
      uses: EndBug/add-and-commit@v9
      with:
        message: 'update spider jar'
        add: 'jar/custom_spider.jar jar/custom_spider.jar.md5'
        push: true
