name: Build custom_spider.jar

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build Release APK
      run: |
        chmod +x gradlew
        ./gradlew :app:assembleRelease --no-daemon --stacktrace --info

    - name: Generate custom_spider.jar
      run: |
        # 清理
        mkdir -p jar
        rm -rf jar/custom_spider.jar jar/custom_spider.jar.md5

        # 提取 classes.jar 从 APK
        unzip -q app/build/outputs/apk/release/app-release.apk classes.jar -d temp_apk
        cp temp_apk/classes.jar jar/custom_spider.jar

        # 生成 MD5
        echo "$(openssl md5 -hex jar/custom_spider.jar | awk '{print $2}')" > jar/custom_spider.jar.md5

        echo "custom_spider.jar 生成成功！"

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: custom_spider.jar
        path: jar/custom_spider.jar

    - name: Commit & Push
      uses: EndBug/add-and-commit@v9
      with:
        message: 'update spider jar'
        add: 'jar/custom_spider.jar jar/custom_spider.jar.md5'
        push: true
