name: Spider

on:
  schedule:
    - cron: '0 0 */3 * *'  # 可删，视需求
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive  # 保留子模块

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Delete old runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        retain_days: 0
        keep_minimum_runs: 2

    # 删除 Customize Spider（可选，自定义删爬虫）
    - name: Customize Spider
      run: |
        # 示例：删除 Ali 爬虫
        # rm -rf app/src/main/java/com/github/catvod/spider/Ali.java
        sed -i "/Doll/d" app/src/main/java/com/github/catvod/debug/MainActivity.java

    - name: Build Release
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease --build-cache --parallel --daemon --warning-mode all

    - name: Generate custom_spider.jar
      run: |
        mkdir -p jar
        rm -rf jar/custom_spider.jar jar/custom_spider.jar.md5

        # 下载工具
        curl -L https://github.com/iBotPeaches/Apktool/releases/download/v2.7.0/apktool_2.7kb.jar -o jar/apktool.jar
        curl -L https://bitbucket.org/JesusFreke/smali/downloads/baksmali-2.5.2.jar -o jar/baksmali.jar

        # 反编译
        java -jar jar/baksmali.jar d app/build/intermediates/dex/release/minifyReleaseWithR8/classes.dex -o jar/Smali_classes

        # 打包
        mkdir -p jar/spider/smali/com/github/catvod/
        cp -r jar/Smali_classes/com/github/catvod/spider jar/spider/smali/com/github/catvod/
        java -jar jar/apktool.jar b jar/spider -o jar/spider.apk

        # 提取 JAR
        unzip -p jar/spider.apk classes.dex > jar/custom_spider.jar

        # 生成 MD5
        echo "$(openssl md5 -hex jar/custom_spider.jar | awk '{print $2}')" > jar/custom_spider.jar.md5

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: custom_spider.jar
        path: jar/custom_spider.jar

    - name: Commit & Push
      uses: EndBug/add-and-commit@v9
      with:
        message: 'update spider jar'
        add: 'jar/custom_spider.jar jar/custom_spider.jar.md5'
